<?php

/**
 * @file
 * .
 *
 *
 * @author SVEN ÄNGERMARK och ANDREAS JOSEFSSON 2015>
 */
//Exmpel
// D
function kiv_sortering_views_query_alter(&$view, &$query) {
  if($view->name === 'kategorier') {
  
  //dpm($view, __FUNCTION__);
    //dpm($query, __FUNCTION__);
    /**
     * Order = (rating * 10) – (hours old / 2)
     * Note: the rating field is divided by 2 because in the DB the rating is out of 100
     */
    // $view->query->orderby[0]['field'] = "(if(field_data_field_rating.field_rating_rating, field_data_field_rating.field_rating_rating,0) / 2) - ROUND((UNIX_TIMESTAMP(NOW())-created)/60/60/2)";
    // $view->query->orderby[0]['direction'] = "DESC";
//
     //$view->query->orderby[0]['field'] = "field_category";
     //$view->query->orderby[0]['direction'] = "DESC";
     //$view->result = array_reverse($view->result);
     
    print("YEY från modulen i sites/all/modules/kiv_sortering/kiv_sortering.module");
    
//    $view->init_display('block_1');
//    $view->display_handler->display->display_options['filters']['your_filter_name']['default_value'] = 'Arkitektur';
//    $view->is_cacheable = FALSE;  
//   $view->execute();
    //print $view->render();
    
    
//        $query->orderby = array(
//          array(
//            'field' => 'nid',
//            'direction' => 'DESC',
//          )
//        );
      }
    
 
}
